# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Coredotnetdemo_CICD02

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.x'
          include-prerelease: true
      
      - name: Build with dotnet
        run: dotnet build --configuration Release
        
      - name: Install dotnet-coverage
        run: dotnet tool install --global dotnet-coverage  
      
      - name: Generate dotnet-coverage report
        run: dotnet-coverage collect 'dotnet test' -f xml  -o 'coverage.xml'
      - name: Fortify on Demand Scan
  # You may pin to the exact commit or the version.
  # uses: fortify/gha-setup-fod-uploader@636f3c3a14aec1747eec5242a02c6349e4f3cce6
        uses: fortify/gha-setup-fod-uploader@v1.0.1
        with:
          version: 1.0.1
          release-id: '202827'
          scan-type: 'DAST'
          tenant-id: 'Accenture_299277767_FMA_100081812'
          api-based-url: 'https://api.trial.fortify.com'
          personal-access-token: 'WHg9S25xb210OzNmbEk2M2txS3p1STJXWEZnNFlg0'
            
      - name: dotnet publish
        run: dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/myapp

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: .net-app

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'githubwebappdemo'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_3CF79FEDEB414197949DCC06CFF9573D }}
          package: .
